(source gnu)
(source melpa)

(depends-on "init-loader")

;; utils
(depends-on "projectile")
(depends-on "flycheck")
(depends-on "smartparens")
(depends-on "ag")
(depends-on "diminish")
(depends-on "volatile-highlights")
(depends-on "expand-region")
(depends-on "anzu")
(depends-on "browse-kill-ring")
(depends-on "easy-kill")
(depends-on "git-gutter-fringe+")
(depends-on "rainbow-delimiters")
(depends-on "ido-ubiquitous")
(depends-on "flx-ido")
(depends-on "smex")
(depends-on "magit")
(depends-on "undo-tree")
(depends-on "company-go")
(depends-on "go-eldoc")
(depends-on "gotest")
(depends-on "git-timemachine")
(depends-on "alert")
(depends-on "google-c-style")
(depends-on "flycheck-google-cpplint")

;; minor modes
(depends-on "nyan-mode")
(depends-on "rspec-mode")
(depends-on "company")
(depends-on "rainbow-mode")

;; major modes
(depends-on "rust-mode")
(depends-on "go-mode")
(depends-on "js2-mode")
(depends-on "yaml-mode")
(depends-on "web-mode")
(depends-on "scss-mode")
(depends-on "swift-mode")
(depends-on "dockerfile-mode")

;; themes
