(source gnu)
(source melpa)

(depends-on "init-loader")

;; utils
(depends-on "projectile")
(depends-on "flycheck")
(depends-on "smartparens")
(depends-on "diminish")
(depends-on "volatile-highlights")
(depends-on "anzu")
(depends-on "git-gutter-fringe+")
(depends-on "rainbow-delimiters")
(depends-on "magit")
(depends-on "undo-tree")
(depends-on "counsel")
(depends-on "spaceline")
(depends-on "smooth-scrolling")

(depends-on "company-go")
(depends-on "go-eldoc")
(depends-on "gotest")
(depends-on "go-dlv")

(depends-on "git-timemachine")
(depends-on "elfeed")

(depends-on "clang-format")

;; ruby dev
(depends-on "yari")
(depends-on "chruby")
(depends-on "prodigy")

;; irc
(depends-on "weechat")

;; exwm
(depends-on "exwm")
(depends-on "password-store")
(depends-on "buffer-move")

;; minor modes
(depends-on "nyan-mode")
(depends-on "minitest")
(depends-on "projectile-rails")
(depends-on "company")
(depends-on "rainbow-mode")

;; major modes
(depends-on "go-mode")
(depends-on "js2-mode")
(depends-on "yaml-mode")
(depends-on "web-mode")
(depends-on "scss-mode")
(depends-on "swift-mode" :git "https://github.com/ap4y/swift-mode")
(depends-on "ledger-mode")
(depends-on "enh-ruby-mode")

;; themes
(depends-on "spacemacs-theme")
