#!/usr/bin/env bash

font="${BAR_FONT:-"-*-tamzen-medium-*-15-*"}"
height="${BAR_HEIGHT:-25}"

get_workspace() {
    workspace=$(canvasctl current_workspace)
    case ${workspace} in
        "1") color="#d08770";;
        "2") color="#ebcb8b";;
        "3") color="#a3be8c";;
        "4") color="#b48ead";;
    esac
    printf "%s" "%{U${color}+u}Workspace $workspace%{U-}"
}

get_buffers() {
    buffers=$(canvasctl list_buffers)
    current=$(canvasctl current_buffer)
    canvasctl list_buffers | while read -r line
    do
        color="#d8dee9"
        if [ "${line}" = "${current}" ]; then
            color="#8fbcbb"
        fi
        printf "  %s  " "%{U${color}+u}${line}%{U-}"
    done
}

get_date() {
    printf "%s\\n" "%{U#5e81ac+u}$(date +"%A, %k:%M")%{U-}"
}

get_mail() {
    mailbox=(~/.mail/ap4y/INBOX/new/*)
    printf "%s\\n" "${#mailbox[@]}"
}

get_song() {
    printf "%.100s\\n" "$(mpc current)"
}

main() {
    # . "${HOME}/.cache/wal/colors.sh"

    pkill lemonbar

    while :; do
        workspace="$(get_workspace)"
        buffers="$(get_buffers)"
        date="$(get_date)"

        printf "%s%s%s  \\n" \
               "%{l}${workspace}" \
               "%{c}${buffers}" \
               "%{r}${date}"
        sleep 1
    done |\

    lemonbar -b -g "x${height}+16+15" \
             -u 2 -F "#4c566a"\
             -n "bar" -f "$font"
}


main "$@"
