#! /bin/sh

bspc config border_width        3
bspc config window_gap          10

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config auto_alternate        true
bspc config auto_cancel           true
bspc config normal_frame_opacity  0.0
bspc config focused_frame_opacity 0.1

bspc config normal_border_color         "#332d29"
bspc config active_border_color         "#817267"
bspc config focused_border_color        "#504339"
bspc config presel_border_color         "#9a875f"
bspc config urgent_border_color         "#9f7155"
bspc config focused_locked_border_color "#9a875f"

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Chromium desktop=^2
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
