font:
  normal:
    family: Tamzen
  size: 10.0
  bold:
    style: normal

window:
  title: term
  padding:
    x: 15
    y: 15

env:
  TERM: xterm-256color

# Base16 NordLight 256 - alacritty color config
# arcticicestudio
colors:
  # Default colors
  primary:
    background: '0xeceff4'
    foreground: '0x4c566a'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xeceff4'
    cursor: '0x4c566a'

  # Normal colors
  normal:
    black:   '0xeceff4'
    red:     '0xbf616a'
    green:   '0xa3be8c'
    yellow:  '0xd08770'
    blue:    '0x5e81ac'
    magenta: '0xb48ead'
    cyan:    '0x88c0d0'
    white:   '0x4c566a'

  # Bright colors
  bright:
    black:   '0x8fbcbb'
    red:     '0xbf616a'
    green:   '0xa3be8c'
    yellow:  '0xd08770'
    blue:    '0x5e81ac'
    magenta: '0xb48ead'
    cyan:    '0x88c0d0'
    white:   '0x8fbcbb'

  indexed_colors:
    - { index: 16, color: '0xd08770' }
    - { index: 17, color: '0x81a1c1' }
    - { index: 18, color: '0xe5e9f0' }
    - { index: 19, color: '0xd8dee9' }
    - { index: 20, color: '0x2e3440' }
    - { index: 21, color: '0x434c5e' }
